name: unit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.18'
      - run: go run cmd/main.go
# jobs:
#   build:
#     runs-on: macos-12
#      steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: swift build
#       - name: Run tests
#         run: swift test

